name: Make Installers for Public Testing
on:
  push:
    branches:
      - main
      - v*
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ['ubuntu', 'windows']
    runs-on: ${{ matrix.os }}-latest
    env:
      build_dir: ./build
      installation_content_dir: ./out
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v2
      - name: Configure a project
        shell: bash  # To allow $VCPKG_INSTALLATION_ROOT on Windows
        env:
          vcpkg_scripts: $VCPKG_INSTALLATION_ROOT/scripts/buildsystems
        run: >
          cmake -S . -B "${{ env.build_dir }}"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="${{ env.vcpkg_scripts }}/vcpkg.cmake"
      - name: Build a project
        run: cmake --build "${{ env.build_dir }}" --config Release
      - name: Copy files for distribution
        run: >
          cmake --install "${{ env.build_dir }}"
          --prefix "${{ env.installation_content_dir }}"
          --strip
      - name: Package files for distribution as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: grammar2code-${{ matrix.os }}
          path: ${{ env.installation_content_dir }}
          if-no-files-found: error
